version: 5.0.0.{build}

branches:
  only:
    - develop
    - master

skip_tags: true

skip_commits:
  files:
    - docs/**/*
    - '**/*.html'

image:
  - Visual Studio 2019

build: off
test: off

artifacts:
  - path: artifacts/*.*nupkg
    name: Packages
  
build_script:
  - ps: .\Build.ps1

deploy:
- provider: NuGet
  name: Prerelease
  api_key:
    secure: AyTQNXkcp/QNILolEJI2jLiG1gW3Zd7HQqHGV2zd1mx6t9byAGtdwoH/NXUNPEdm
  on:
    branch: develop
- provider: NuGet
  name: Release
  api_key:
    secure: AyTQNXkcp/QNILolEJI2jLiG1gW3Zd7HQqHGV2zd1mx6t9byAGtdwoH/NXUNPEdm
  on:
    branch: master
