version: 4.2.1.{build}

branches:
  only:
    - develop
    - master

skip_tags: true

skip_commits:
  files:
    - docs/**/*
    - '**/*.html'

image:
  - Visual Studio 2017

build: off
test: off

artifacts:
  - path: artifacts/*.*nupkg
    name: Packages
  
build_script:
  - ps: .\Build.ps1

deploy:
- provider: NuGet
  name: Prerelease
  api_key:
    secure: ZE3aLThP4rx5y4PzUOGw2Qx1C8h2bzx1fqVJSdX8bBnGjqYK6fXUrg9migGVhX9y
  on:
    branch: develop
- provider: NuGet
  name: Release
  api_key:
    secure: ZE3aLThP4rx5y4PzUOGw2Qx1C8h2bzx1fqVJSdX8bBnGjqYK6fXUrg9migGVhX9y
  on:
    branch: master
